[General]
# Force the graphic compositor to spawn the session directly inside the greeter VT
ReuseSession=true

[Theme]
Current=sugar-candy

[Users]
# Explicitly target your modern service manager stack as the base target session
RememberLastSession=true
DefaultSession=hyprland-uwsm.desktop
