hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
	hl.exec_cmd("uwsm app -- hyprpaper")
	hl.exec_cmd("uwsm app -- sh -c  'sleep 3 && awww-daemon'")
	hl.exec_cmd("uwsm app -- waybar")
	hl.exec_cmd("uwsm app -- mako")
	hl.exec_cmd("uwsm app -- quickshell -c quick-settings")
end)
