font_family Consolas
font_size 10

background #000000
foreground #ffffff

# Clear visible screen and wipe older scrollback history
map ctrl+l combine : clear_terminal scrollback active : send_text normal,application \x0c

# Copy the entire active session to clipboard
map ctrl+shift+y launch --stdin-source=@screen_scrollback --type=clipboard
